
const essayEntries = [
    {
    id: 1,
    title: "Gumtree Critique", 
    text: " <p>1 Introduction The website I decided to analyse was the Gumtree website (Gumtree.co.za). The main reason for this being that they provide a useful service to people within the country of South Africa in which they get to purchase or sell any items they wish to. The web developers at Gumtree have the responsibility to deliver a site that is usable for all people seeking the service on whatever platform they may be using. Due to the service that they facilitate, which involves the use of sensitive information like contact information, they also have a strong imperative to try make sure that users of the website that sell items are not frauds or people with malicious intent. The Gumtree website operates itself with the user’s best interest in mind. Their UI and UX design is acceptable overall, although there are certainly places that could be improved upon and tweaked when it comes to the presentation of items and the interface.</p>" +

  "<p> Introduction The website I decided to analyse was the Gumtree website (Gumtree.co.za). The main reason for this being that they provide a useful service to people within the country of South Africa in which they get to purchase or sell any items they wish to. The web developers at Gumtree have the responsibility to deliver a site that is usable for all people seeking the service on whatever platform they may be using. Due to the service that they facilitate, which involves the use of sensitive information like contact information, they also have a strong imperative to try make sure that users of the website that sell items are not frauds or people with malicious intent. The Gumtree website operates itself with the user’s best interest in mind. Their UI and UX design is acceptable overall, although there are certainly places that could be improved upon and tweaked when it comes to the presentation of items and the interface. </p> "  +

  "<p> 2 UX Elements and IA Interface While the screen can at times feel a bit too cluttered with multiple elements presented at a time, it is still an overall a visually appealing site and a lot of those on-screen items are required. There is also a good amount of navigation tools present to the user so that they can easily and quickly search for what they want and apply the appropriate features.</p> "  +
  
  "<p> 2. 1 Information Presentation The user interface for the most part addresses the potential needs users might have by instantly making the most important information more prominent at each step. For the most part, users can access whatever information it is that they may be curious about finding. The most important information on the website stands out for users to identify. This information is placed in the biggest box containers with larger text and a foreground colour that differentiates it from the page background. An example of this can be seen on the homepage of the web site, where the most important information about topics such as safely trading on the website is placed in big containers with a colourful background.</p>" +
  
  "<p> 2.2 Functionality In terms of the overall functionality of the website, it is for the most part responsive to screen size changes which is a very important aspect. The background colour of a particular section, along with the list of items within that section do not perfectly fit as the item boxes overlap the background colour in which they are supposed to be contained in. Although this one of the only issues found with responsiveness. The other one being as the screen size increases and we utilise larger screens, they tend to not be as optimized to utilise space as well as they could have been. For the largest screen, it feels like this could have been done to allow space for adds but it overall detracts from the visual appeal of the website, when we discuss topics about visual weight because the width of the screen doesn’t feel fully utilized. It is therefore reasonably responsive with only a few issues, while remaining useful for a wide range of users that can only access the website on certain devices. The ease of use and functionality is maintained across multiple platforms/devices.</p>" +
  
  "<p> 2.3 Number and complexity of choices The number and complexity of choices on the website remain practical. The website has a lot of categories but that is mainly due to it catering to multiple items and products that are for sale. That plays into the overall functionality available to the user and so the large number of categories is reasonable. It also makes sure to present users with actions they may want to utilise when trying to commit a purchase like being able to filter their searches, and order how the results are returned, or even an input field where they can suggest an offer price to a seller. It overall does not take too long to make decisions on what to do when the moment comes because processes are not too complex and the objects on the screen are rarely overwhelming in presentation.</p>" +
  
  "<p> 2.4 Incomplete or interrupted tasks There is a system that will indicate users when a task is incomplete, however it is not as clear as it could be. It is a pop up with a limited duration that will show up each time a user navigates around the web site, but opting for something that is a lot more permanent could be a better choice than the disappearing pop up. There is also no indication of the number of items liked which would be useful as a visual indicator and reminder to users that there are some items in which they are considering purchasing. It could have made this way for simplicity and that the button for all the saved items is present, it would be a useful tool and reminder so returning users can always pick up from where they left off when revisiting the site.</p>" +
  
  "<p> 2.4 Navigation Gumtree uses a wide range of good navigation tools that ease the experience for users significantly. The search functionality comes coupled with filters that help users tailor their searches to what they are looking for and specify things as much as they possibly can. An example of this is the “filter and refine” options that allow a user to specify a price range of a search as well as whether that price might be negotiable or fixed. This was a necessary feature for Gumtree to implement as a service since it is based on users finding what they wish to purchase. The only drawback when It comes to ease of navigation on the website is the lack of tools that make traversal a lot faster. The navigation bar does not move as users scroll down a page, and there are no buttons that jump to specific sections like a back to top button. Having such a feature set would make navigation that much easier, as users could jump between sections and categories that much quicker. Call to action elements on the web page are good at guiding users to any actions they may wish to perform on the web page. They are made distinct and clear most of the time as big green buttons that can be clicked on, and are also placed in areas users would easily spot. The placement of the post free add button being at the top right of the navigation bar is good for when users first navigate to page but the only downside with this button is that it is not always present due to the navigation bar sticking at the top. The “post an add” button is a very important feature and it being more reachable and easily identifiable would be a benefit.</p>" +
  
  " <p> 3 UI Elements The UI design is visually appealing and smartly combines the colour scheme of green, ivory, black and light brown to create a web page that seems to be presenting a friendly and comfortable demeanour. Green is a very down toearth color that can have a balancing and harmonizing effect and is very stable. Brown helps bring a feeling of warmth and wholesomeness to designs. Ivory - In design, ivory can lend a sense of elegance and calm to a site. [4] All of these add up to build that comforting effect. The website aims to feel user-friendly and create a sense of comfort. The company states on their about page that they are \"a place everyone trusts, a familiar space that’s easy to navigate, and a classified site that just works – whether via your mobile phone or desktop.\"[3]. The use of soft shapes and lighter colours point to how the web page is primary trying to make users feel more invited and at-ease. Buttons on website are made with rounded edges, and the icons for the categories are made with a variety of pastel colours. </p>" +
  
  "<p> The font selected for the web page is both easy and comfortable for users to read mainly because of the use of a very simple font that is very legible and it reasonably spaced. The colour scheme also mainly contrasted well enough by using dark colours on a light background and vice versa in other sections like the navigation panel, or the footer. The elements of the page are aligned and there is a very deliberate focus on harmony within the design and placement of information to further enhance that feeling of trust and comfort.</p>" +
  
  "<p>  4 Ethics of Design Gumtree as a website works for the users best interests for the most part but there are still a few issues within their ethics that can be improved upon. The site is usable and simplified for users and meets the visual presentation standard that they need to, however the one unethical pattern I managed to identify was that the web page will automatically tick a box to sign up to their newsletter service, and the responsibility is on users to spot that and decide whether or not they wish to receive those promotions. The only issue with this is that it is an option that could be made more transparent to users.</p>" +
  
  "<p> 4.1 Privacy and security for users As a website that supports interaction between real people that will end up trading with each other, it is own Gumtree to try enforce that users that sell on their site are legitimate people that sell items in good faith. They perform this well by providing articles based around user safety and security, and this information is given priority on the presentation of the page. Verified users that present information are also granted greater priority on searches which creates a positive culture within the user base that sells. The web page also presents key information about the people you will be making your purchase from, such as what types of verification methods they have carried out and how long they have been selling on the website. This effort to make this as transparent as possible is commendable ethically and goes to show how Gumtree prioritises the user's needs and presents benevolent intent. There is still however responsibilty on Gumtree to also use the user information that they collect from users in an ethical manner since they also verify sensitive documents such as IDs and Passports.</p>" +
  
  "<p> 4.2 Accessibility To test the web page for accessibility, I used Accessibility Checker which is a free web-based audit tool that scans your website for major legislation's around the world. Upon analyses, the gumtree website failed some cases that would provide accessibility to visually impaired users that may need to use a screen reader. These included a lack of unique ARIA ID's and access key values which become a problem when these users might not have enough information on the description of links. It is an issue for their usability and experience of the page.</p>" +
  
  "<p> 5 Conclusion In conclusion, Gumtree as a website provides makes effort to provide the service, they do for users ethically. The user experience is designed to be easy and usable for customers and the user interface aims to create a sense of comfort and trust with users. There are a few short comings that however could be improved upon.</p>" +
  
  "<p> References</p>" +
  
  "<p> [1] Goldberg, P. (2021) UX_The basics - How to, WSOA3028A: Interactive Media 3A, University of the Witwatersrand</p>" +
  
  "<p> [2] Goldberg, P. (2021) ETHICS OF UX PRACTICE, WSOA3028A: Interactive Media 3A, University of the Witwatersrand</p>" +
  
  "<p> [3] About Us – Gumtree South Africa (2023) Available at :https://guide.gumtree.co.za/hc/en-us/articles/11566527396881-About-Us (Accessed: May 1, 2023).</p>" +
  
  "<p> [4]Color Theory for Designers, Part 1: The Meaning of Color (2021) Available at: https://www.smashingmagazine.com/2010/01/color-theory-for-designers-part-1-the-meaning-of-color (Accessed: May 1, 2023)</p>" +
  
  "<p> [5] 8 Free Web-Based Website Accessibility Evaluation Tools: Justin Mifsud (NA) Available at :https://usabilitygeek.com/10-free-web-based-web-site-accessibility-evaluation-tools (Accessed: May 1, 2023)</p>" 
   
   ,},
    
      {id: 2,
      title: "Statement on AI Mitigation", 
      text: " <p> The Centre for AI Safety (CAIS) released a statement on AI in which they claim that the risk AI presents should be placed on as high of a priority as pandemics and nuclear wars. The statement is backed by high-ranking individuals as signatories and is calling for the regulation of the development of AI, as well as more funding and research to be placed in the sector of AI. The issue with this however is if CAIS has genuine intentions of dealing with AI risk or if it is more focused on solidifying the status of the current leaders in AI innovation as the signatories stand to benefit greatly from overseeing AI regulation. CAIS brings up valuable points of concern, but they also stand in a position to widen the current digital divide and centralize the control of AI.</p>" +
     
      "<p> CAIS is a San Francisco-based research and field-building nonprofit. [1] They claim that their mission is to mitigate the societal-scale risk involved with the progress and development of AI by building the field of AI through research and advocacy. CAIS states that it is far too “difficult to voice concerns about some of advanced AI’s most severe risks” so they instead utilize a short statement that they claim was made to start a discussion. The manifesto is so short it is concerning, and just below it, the statement is shown to be backed by signatories that are all either experts in the field of AI research, or notable figures in general. The delivery of it calls into question if there are any ulterior motives at play with the proposition. </p>" +

       "<p> The statement itself seems tailored to draw attention and spark discussion as it claims that AI risk is equal in importance to pandemics and war. It is important to question if AI does indeed pose as much of a risk to humanity at the level of extinction however the choice of wording throughout the CAIS page makes it feel like an attempt at fearmongering by using preconceived notions and fears that people have of superintelligent AI against the public. While the in-depth AI risks present some very practical dangers of AI, there are also some elements of AI risk brought up that are highly hypothetical in nature, to the point of the Pixar movie WALL-E being referenced on the website. </p>" +

       "<p> Legitimate concerns are being brought up by the statement that should not be dismissed but some scenarios are far too hypothetical. As such it is fair that there are even more concerns in place that should question the intention, and transparency of the messengers. The mission of CAIS is detailed as helping policymakers and officials make better decisions when it comes to AI development. As well as to continue to expand research and field building in the sector of AI study as this sector believes AI can profoundly benefit the world. </p>" +

       "<p>Risk management to ensure AI benefits the world is undeniably a crucial aspect to consider when developing new technology and it is sensible to tackle the issues presented by AI as it is completely new ground, and we are thus bound to run into ethical concerns. The risks outlined by CAIS tackle some valid concerns that can be observed affecting the current landscape of internet culture.</p>" +

       "<p>Misinformation is one of the risks highlighted by CAIS that has had a visible impact on the potential danger that AI has. AI can generate image, audio, and video content easily and these have resulted in a lot of ethical problems, violations, and concerns about the use of AI. AI deep fakes that make use of audio can be used to create false representations of an individual without their consent. </p>" +

       "<p>It started harmlessly with memes of presidents playing Minecraft together, but it can easily be utilized maliciously to create false propaganda and influence gullible groups of people who would not detect the uncanny effect of the video. There are a great number of examples where false information being spread led directly to tragedies. This is a side of AI that needs restriction and control or a method to validate or counter false data. Even large models like ChatGPT are prone to a phenomenon called “hallucinations”, in which fabricated or false information is repeated. [2] </p>" +

       "<p>The combination of misinformation and AI can lead to the radicalization of individuals. This Is due to AI having no real discernment and simply being focused on optimizing the task it has been given. This risk is expressed in AI recommender systems which prioritize what a user will click on, rather than if the content is potentially harmful for them. [3] There was also an alleged case in which an AI chatbot convinced someone to kill themselves. [2] As such, AI can push harmful information that reconfirms biased information that places marginalized groups in very real danger of ultras.</p>" +

       "<p>AI carries out its duties with no regard to copyright laws or the intellectual property of some of the sources that it draws information from. AI and machine learning in their current state work on pattern recognition based on data that has been supplied to them. As such, it raises concern when there are cases of AI being trained on an online artist’s work without the consent of the artist.[4] This results in the AI becoming capable of replicating an artist’s unique style. The issue not being that the machine learns but rather the fact this data and information has been mined without their consent. </p>" +

       "<p>Yet another issue that stems from the data AI is trained from is the belief that AI is some form of unbiased metric that provides the correct judgment. Some judicial experts claim and believe that AI programs reduce human bias in law and lead to fairer sentences. They have a firm belief that “Empirically grounded questions of predictive risk analysis play to the strengths of machine learning, automated reasoning, and other forms of AI.[5]” However, AI should not serve as a replacement for moral and ethical considerations in the real world. The truth is that the data being fed to AI is not objectively neutral and contains biases. This is prevalent and can be seen in the awful Google face recognition incident. [6] If AI like that continues to be created with faulty data at the base level, then it is bound to replicate biases and false information. Resulting in it being used to perpetuate harmful stereotypes and discriminatory practices against certain groups of people. As evidenced by predictive policing algorithms, data is biased. [7]</p>" +

       "<p>Badly trained AI created by groups of power that are not part of marginalized communities adversely affects the marginalized due to the oversight of the people making the system. Thus, at the end of the day, it rings true that “artifacts do indeed have politics.” [8]</p>" +

       "<p>CAIS brings up the possible risk of AI being controlled by a select few groups of people, and as such they may be able to be the ones whose values are propagated throughout the media. This is an interesting idea and risk that acknowledges the existence of an imbalance of power. Some argue that the exponentially increasing compute and data barriers to entry make AI a centralizing force. [3] CAIS expresses this ordeal, but the issue is that a lot of the signatories of CAIS are the very individuals that represent the current imbalance of power within the digital space, and with this move, it is possible that the imbalance of power could potentially widen even further. </p>" +

       "<p>CAIS presents some genuine AI risks that are currently plaguing the internet, but these concerns are coupled with some more extreme scenarios of AI Risk. The manifesto is somewhat misrepresentative of AI in its current form as it is not truly super-intelligent. One of the three founders of AI, Yann LeCun, reacts skeptically towards the statement claiming that “Until we have a basic design for even dog-level AI, discussing how to make it safe is premature.” [9]. A lot of the AI risks certainly do feel far too premature in concern. The possible reason for the CAIS manifesto could be to utilize the unknown quality of AI development and to hint at how rapidly such complex superintelligent systems are close to being in place. This could be enough to make officials and policymakers allow the signatories influence over the regulation of AI, and as such slow down progress for any competition and maintain their stake as the AI leaders.</p>" +

       "<p>One of the AI risks laid out by CAIS outwardly states it wants to regulate and make access to AI more difficult as “Easy access to powerful AI systems increases the risk of unilateral, malicious usage.” [3] It cites the reasoning for this to prevent bad actors from misusing such tech, but the problem with the statement is the crux it places on developing industries and their advancements with AI. There seems to be that reliance on fear over the danger of AI in humans.</p>" +

       "<p>Another example brought up was the possibility of AI being deceptive to try to gain human approval in the performance of its tasks. However, when looked at historically it is humans who have been incredibly deceptive with how they market their inventions. Like VW hiding emission rates with software, Uber faking their number of cars within a city for regulation, and the Boeing MCAS system. [6]. These were real-world ethical issues caused by large corporations in power. </p>" +

       "<p>A concerning piece of information related to the Manifesto is the information that Open AI leaders published an article based on the governance of Superintelligence that “asked everyone to stop worrying about current AI models and to instead focus on legislating about future danger: would consider withdrawing ChatGPT from the continent if the European Union advances in its “over-regulation,” [9].</p>" +

       "<p>Information such as that suggests that the statement could have been made to excuse these companies for not making their practices open and transparent with regulatory bodies and to ensure that they are the only experts that need to be consulted on matters of AI. If CAIS were to achieve its goal of being the biggest advocate for the regulation of AI development, it would potentially result in a system in which the development and entry of other companies into the AI market are stifled. </p>" +

       "<p>DAIR (Distributed AI Research Institute), is a similar non-profit organization that comes across as a lot more concerned about the AI-related issues in current times. Their model is based on placing communities affected by design at the center. They are a lot more focused on the empowerment and protection of marginalized communities through their inclusion and collaboration with these communities in the development of AI and the decentralization of control of information. The approach that DAIR considers claims to believe that research “should center the voices and experiences of those most impacted by technology and should be rooted in their communities.”[10] Which is similar and in line with the Design Justice Network Principles project goals. </p>" +

       "<p>In conclusion, some of the issues and publicity caused by the CAIS statement were good in terms of considering AI risks, and the impact it has on society. However, despite the dangers that AI risks pose, it is worth noting that there is also the risk of the current leaders of AI utilizing the potential role of being advisory council to solidify their status and control over AI development for the entire globe. The leaders of AI companies need to become more transparent. </p>" +
       "<p>References</p>" +
       "<p>[1] - Center for AI Safety (2023) https://www.safe.ai/statement-on-ai-risk : (Accessed: June 25, 2023)</p>" +
       "<p>[2] – Robot takeover? Not quite. Here’s what AI doomsday would look like | Technology | The Guardian (Accessed: June 23, 2023)</p>" +
       "<p>[3] Center for AI Safety (2023) AI Risk – CAIS https://www.safe.ai/ai-risk - (Accessed: June 25, 2023)</p>" +
       "<p>[4] Chloe Xiang (2023) Artists Are Suing Over Stable Diffusion Stealing Their Work for AI Art  https://www.vice.com/en/article/dy7b5y/artists-are-suing-over-stable-diffusion-stealing-their-work-for-ai-art (Accessed: June 25, 2023)</p>" +
       "<p>[5] - Darrell M. West and John R. Allen (2018) How artificial intelligence is transforming the world - https://www.brookings.edu/research/how-artificial-intelligence-is-transforming-the-world/ (Accessed: June 24, 2023)</p>" +
       "<p>[6] CraftHub Events (2019)  Bryan Cantrill - Andreessen's Corollary: Ethical Dilemmas in Software Engineering:  https://www.youtube.com/watch?v=0wtvQZijPzg</p>" +
       "<p>[7] Damien Patrick Williams (2020) Fitting the description: historical and sociotechnical elements of facial recognition and anti-black surveillance, Journal of Responsible Innovation </p>" +
       "<p>[8] Costanza-Chock, S., 2020. Introduction: # TravelingWhileTrans, Design Justice, and Escape from the Matrix of Domination. Design Justice, 1.</p>" +
       "<p>[9] – Jordi Perez Colome (2023) Why are the people who pushed for artificial intelligence now signing so many doomsday manifestos? https://english.elpais.com/science-tech/2023-06-03/why-are-the-people-who-pushed-for-artificial-intelligence-now-signing-so-many-doomsday-manifestos.html : (Accessed: June 24, 2023)</p>" +
       "<p>[10] Distributed AI Research Institute (2023) https://www.dair-institute.org/ (Accessed: June 25, 2023)</p>" 
       ,},

    ];


function PopulateEssay(option){
    let essayEntry = document.getElementById("essay");
    essayEntry.innerHTML = essayEntries[option - 1].title;

    let weekTitle = document.getElementById("weekname");
    weekTitle.innerHTML = devEntries[option - 1].title;
}